language: node_js

node_js:
  - "5"

cache:
  directories:
    - node_modules

before_install:
  - "npm config set spin false"
  - "npm --version"
  - npm install grunt-cli -g
  - "phantomjs --version"
  - "rm -f /tmp/*.dmp"

install:
  - "npm install"
  - "bower install"