language: node_js

dist: trusty

node_js:
  - "6"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta

before_install:
  - "export CHROME_BIN=google-chrome-beta"
  - "npm config set spin false"
  - "npm --version"
  - "npm install coveralls"
  - "rm -f /tmp/*.dmp"
  - "google-chrome --version"

install:
  - "npm install"

after_success:
  - "cat test/coverage/*/lcov.info | node_modules/coveralls/bin/coveralls.js"

notifications:
  email:
    recipients:
      - travis@snew.io
    on_success: change
    on_failure: always
